set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports btn0]
set_property IOSTANDARD LVCMOS33 [get_ports btn1]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property PACKAGE_PIN F14 [get_ports clk]
set_property PACKAGE_PIN G1 [get_ports {RxData[7]}]
set_property PACKAGE_PIN G2 [get_ports {RxData[6]}]
set_property PACKAGE_PIN F1 [get_ports {RxData[5]}]
set_property PACKAGE_PIN F2 [get_ports {RxData[4]}]
set_property PACKAGE_PIN E1 [get_ports {RxData[3]}]
set_property PACKAGE_PIN E2 [get_ports {RxData[2]}]
set_property PACKAGE_PIN E3 [get_ports {RxData[1]}]
set_property PACKAGE_PIN E5 [get_ports {RxData[0]}]
#set_property PACKAGE_PIN J2 [get_ports btn0]
set_property PACKAGE_PIN J5 [get_ports btn1]
set_property PACKAGE_PIN V2 [get_ports reset]
set_property PACKAGE_PIN U2 [get_ports {sw[7]}]
set_property PACKAGE_PIN U1 [get_ports {sw[6]}]
set_property PACKAGE_PIN T2 [get_ports {sw[5]}]
set_property PACKAGE_PIN T1 [get_ports {sw[4]}]
set_property PACKAGE_PIN R2 [get_ports {sw[3]}]
set_property PACKAGE_PIN R1 [get_ports {sw[2]}]
set_property PACKAGE_PIN P2 [get_ports {sw[1]}]
set_property PACKAGE_PIN P1 [get_ports {sw[0]}]

set_property BITSTREAM.STARTUP.STARTUPCLK JTAGCLK[current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property PACKAGE_PIN V12 [get_ports Rx]
set_property PACKAGE_PIN U11 [get_ports Tx]
set_property IOSTANDARD LVCMOS33 [get_ports Rx]
set_property IOSTANDARD LVCMOS33 [get_ports Tx]
